### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by lconstable** [banteg/docsend#1]
For some docsends, this works perfectly. For others, I get the following error sequence. Love the tool, but not sure what's not functioning there.
<img width="638" alt="Screen Shot 2019-03-28 at 12 40 45 PM" src="https://user-images.githubusercontent.com/2267969/55187629-c6736780-5156-11e9-9f44-772f6e31712d.png">

**Comment by jackrvaughan** [comment]
https://github.com/banteg/docsend/pull/2 should resolve this
